server:
  port: 8080
  servlet:
    context-path: /user-spring 

management:
  endpoints:
    web:
      exposure:
        include: "*"
      
spring:
  config:
    import: 
    - application-mariadb.yml
  application:
    name: user-spring
  data:
    rest:
      basePath: /api

logging:
  level:
    '[com.htdp1.userspring]': debug

